### Import Libraries

In [3]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV  # Hyperparameyer tuning

from sklearn.preprocessing import MinMaxScaler, StandardScaler  #Feature Scaling

from sklearn.neighbors import KNeighborsClassifier

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

### Data Gathering

In [4]:
df = pd.read_csv('heart.csv')
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [6]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [4]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

#### MinMax Scaler

In [7]:
age_63 = (63-29)/(77-29)
age_63

0.7083333333333334

In [8]:
age_77 = (77-29)/(77-29)
age_77

1.0

In [9]:
age_29 = (29-29)/(77-29)
age_29

0.0

#### Standrad Scaler

In [10]:
age_63 = (63-54.366337)/(9.082101)
age_63

0.950623980068048

In [12]:
X = df.drop('target', axis=1)
y = df['target']

#### MinMax Scaler (Normalization)

In [14]:
# Create instance of MInMax Scaler (Normalization)
minmax_scaler = MinMaxScaler()
X_scaled = minmax_scaler.fit_transform(X)
X_scaled
X_minmax_df = pd.DataFrame(X_scaled, columns=X.columns)
X_minmax_df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,0.708333,1.0,1.000000,0.481132,0.244292,1.0,0.0,0.603053,0.0,0.370968,0.0,0.00,0.333333
1,0.166667,1.0,0.666667,0.339623,0.283105,0.0,0.5,0.885496,0.0,0.564516,0.0,0.00,0.666667
2,0.250000,0.0,0.333333,0.339623,0.178082,0.0,0.0,0.770992,0.0,0.225806,1.0,0.00,0.666667
3,0.562500,1.0,0.333333,0.245283,0.251142,0.0,0.5,0.816794,0.0,0.129032,1.0,0.00,0.666667
4,0.583333,0.0,0.000000,0.245283,0.520548,0.0,0.5,0.702290,1.0,0.096774,1.0,0.00,0.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,0.583333,0.0,0.000000,0.433962,0.262557,0.0,0.5,0.396947,1.0,0.032258,0.5,0.00,1.000000
299,0.333333,1.0,1.000000,0.150943,0.315068,0.0,0.5,0.465649,0.0,0.193548,0.5,0.00,1.000000
300,0.812500,1.0,0.000000,0.471698,0.152968,1.0,0.5,0.534351,0.0,0.548387,0.5,0.50,1.000000
301,0.583333,1.0,0.000000,0.339623,0.011416,0.0,0.5,0.335878,1.0,0.193548,0.5,0.25,1.000000
302,0.583333,0.0,0.333333,0.339623,0.251142,0.0,0.0,0.786260,0.0,0.000000,0.5,0.25,0.666667

#### Standrad Scaler (Standradization)

In [16]:
std_scaler = StandardScaler()
X_scaled = std_scaler.fit_transform(X)
X_scaled
X_std_df = pd.DataFrame(X_scaled, columns=X.columns)
X_std_df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,0.952197,0.681005,1.973123,0.763956,-0.256334,2.394438,-1.005832,0.015443,-0.696631,1.087338,-2.274579,-0.714429,-2.148873
1,-1.915313,0.681005,1.002577,-0.092738,0.072199,-0.417635,0.898962,1.633471,-0.696631,2.122573,-2.274579,-0.714429,-0.512922
2,-1.474158,-1.468418,0.032031,-0.092738,-0.816773,-0.417635,-1.005832,0.977514,-0.696631,0.310912,0.976352,-0.714429,-0.512922
3,0.180175,0.681005,0.032031,-0.663867,-0.198357,-0.417635,0.898962,1.239897,-0.696631,-0.206705,0.976352,-0.714429,-0.512922
4,0.290464,-1.468418,-0.938515,-0.663867,2.082050,-0.417635,0.898962,0.583939,1.435481,-0.379244,0.976352,-0.714429,-0.512922
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,0.290464,-1.468418,-0.938515,0.478391,-0.101730,-0.417635,0.898962,-1.165281,1.435481,-0.724323,-0.649113,-0.714429,1.123029
299,-1.033002,0.681005,1.973123,-1.234996,0.342756,-0.417635,0.898962,-0.771706,-0.696631,0.138373,-0.649113,-0.714429,1.123029
300,1.503641,0.681005,-0.938515,0.706843,-1.029353,2.394438,0.898962,-0.378132,-0.696631,2.036303,-0.649113,1.244593,1.123029
301,0.290464,0.681005,-0.938515,-0.092738,-2.227533,-0.417635,0.898962,-1.515125,1.435481,0.138373,-0.649113,0.265082,1.123029
302,0.290464,-1.468418,0.032031,-0.092738,-0.198357,-0.417635,-1.005832,1.064975,-0.696631,-0.896862,-0.649113,0.265082,-0.512922

### Train Test Split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X_minmax_df, y, 
                                            test_size=0.20, random_state=42)

In [19]:
X_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
132,0.270833,1.0,0.333333,0.245283,0.385845,0.0,0.5,0.694656,0.0,0.000000,1.0,0.00,0.666667
202,0.604167,1.0,0.000000,0.528302,0.328767,0.0,0.0,0.305344,1.0,0.129032,1.0,0.00,1.000000
196,0.354167,1.0,0.666667,0.528302,0.239726,0.0,0.5,0.580153,0.0,0.580645,0.5,0.00,0.666667
75,0.541667,0.0,0.333333,0.386792,0.283105,0.0,0.0,0.687023,0.0,0.225806,0.5,0.00,0.666667
176,0.645833,1.0,0.000000,0.216981,0.237443,1.0,0.5,0.679389,1.0,0.225806,1.0,0.50,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
188,0.437500,1.0,0.666667,0.433962,0.244292,0.0,0.5,0.702290,0.0,0.096774,0.5,0.25,1.000000
71,0.458333,1.0,0.666667,0.000000,0.230594,0.0,0.5,0.633588,1.0,0.000000,1.0,0.25,1.000000
106,0.833333,1.0,1.000000,0.622642,0.246575,1.0,0.0,0.458015,0.0,0.016129,0.5,0.25,0.666667
270,0.354167,1.0,0.000000,0.245283,0.280822,0.0,0.0,0.557252,0.0,0.129032,1.0,0.00,1.000000
102,0.708333,0.0,0.333333,0.433962,0.157534,0.0,0.5,0.824427,0.0,0.000000,1.0,0.50,0.666667

In [18]:
X_test

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
179,0.583333,1.0,0.000000,0.528302,0.342466,0.0,0.0,0.312977,1.0,0.096774,0.5,0.25,0.333333
228,0.625000,1.0,1.000000,0.716981,0.369863,0.0,0.0,0.671756,0.0,0.032258,0.5,0.00,1.000000
111,0.583333,1.0,0.666667,0.528302,0.000000,1.0,0.5,0.778626,0.0,0.032258,1.0,0.25,1.000000
246,0.562500,0.0,0.000000,0.377358,0.646119,0.0,0.0,0.603053,1.0,0.306452,0.5,0.50,1.000000
60,0.875000,0.0,0.666667,0.150943,0.317352,1.0,0.0,0.450382,0.0,0.000000,1.0,0.25,0.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,0.833333,1.0,0.666667,0.433962,0.292237,0.0,0.0,0.572519,0.0,0.322581,0.5,0.75,1.000000
104,0.437500,1.0,0.666667,0.330189,0.159817,0.0,0.5,0.702290,0.0,0.000000,1.0,0.00,0.666667
300,0.812500,1.0,0.000000,0.471698,0.152968,1.0,0.5,0.534351,0.0,0.548387,0.5,0.50,1.000000
193,0.645833,1.0,0.000000,0.481132,0.356164,0.0,0.0,0.541985,1.0,0.451613,0.5,0.50,1.000000
184,0.437500,1.0,0.000000,0.528302,0.267123,0.0,0.0,0.435115,0.0,0.419355,0.5,0.00,1.000000

### Train Model

In [20]:
knn_class = KNeighborsClassifier(n_neighbors=11, p=2)
knn_class.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=11)

In [21]:
y_pred = knn_class.predict(X_test)
y_pred

array([0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [22]:
y_test[:5]

179    0
228    0
111    1
246    0
60     1
Name: target, dtype: int64

In [23]:
y_pred[:5]

array([0, 0, 1, 0, 1], dtype=int64)

#### Evaluation

In [24]:
#Confusion Matrix
con_matrix = confusion_matrix(y_test, y_pred)
con_matrix

array([[26,  3],
       [ 8, 24]], dtype=int64)

In [25]:
(26+24)/61

0.819672131147541

In [26]:
#Accuracy
accuracy= accuracy_score(y_test, y_pred)
accuracy

0.819672131147541

In [22]:
# Classification Report
class_report = classification_report(y_test, y_pred)
print(class_report)

              precision    recall  f1-score   support

           0       0.75      0.93      0.83        29
           1       0.92      0.72      0.81        32

    accuracy                           0.82        61
   macro avg       0.83      0.82      0.82        61
weighted avg       0.84      0.82      0.82        61

### Hyperparameter Tuning

#### Grid SearchCV

In [29]:
k = np.arange(2,15)
k

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
k = np.arange(2,50)
p = [1,2]
hyp = {'n_neighbors': k, "p":p}

In [44]:
knn = KNeighborsClassifier()
gscv_knn_model = GridSearchCV(knn,hyp,cv=5)
gscv_knn_model.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19]),
                         'p': [1, 2]})

In [45]:
gscv_knn_model.best_estimator_

KNeighborsClassifier(p=1)

In [46]:
gscv_knn_model.best_params_

{'n_neighbors': 5, 'p': 1}

#### Randomized Search CV

In [48]:
knn = KNeighborsClassifier()
rscv_knn_model = RandomizedSearchCV(knn,hyp,cv=5)
rscv_knn_model.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(),
                   param_distributions={'n_neighbors': array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
                                        'p': [1, 2]})

In [49]:
rscv_knn_model.best_params_

{'p': 1, 'n_neighbors': 48}

In [37]:
knn_class_gs = KNeighborsClassifier(n_neighbors=5, p=1)
knn_class_gs.fit(X_train, y_train)

KNeighborsClassifier(p=1)

In [38]:
y_pred_gs = knn_class_gs.predict(X_test)
y_pred_gs

array([0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [39]:
#Accuracy
accuracy_gs= accuracy_score(y_test, y_pred_gs)
accuracy_gs

0.819672131147541

In [50]:
knn_class_rs = KNeighborsClassifier(n_neighbors=48, p=1)
knn_class_rs.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=48, p=1)

In [51]:
y_pred_rs = knn_class_rs.predict(X_test)
y_pred_rs

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [52]:
#Accuracy
accuracy_rs= accuracy_score(y_test, y_pred_rs)
accuracy_rs

0.8852459016393442

In [53]:
from sklearn.metrics import roc_auc_score, roc_curve

In [54]:
roc_auc_score(y_test, y_pred)

0.8232758620689656

In [56]:
roc_auc_score(y_test , y_pred_rs)

0.8841594827586207